/* 
 * ProcessMaker API
 *
 * This ProcessMaker I/O API provides access to a BPMN 2.0 compliant workflow engine api that is designed to be used as a microservice to support enterprise cloud applications.  The current Alpha 1.0 version supports most of the descriptive class of the BPMN 2.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@processmaker.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProcessMaker.PMIO.Api;
using ProcessMaker.PMIO.Model;
using ProcessMaker.PMIO.Client;
using System.Reflection;

namespace ProcessMaker.PMIO.Test
{
    /// <summary>
    ///  Class for testing FlowAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlowAttributesTests
    {
        // TODO uncomment below to declare an instance variable for FlowAttributes
        //private FlowAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlowAttributes
            //instance = new FlowAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlowAttributes
        /// </summary>
        [Test]
        public void FlowAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlowAttributes
            //Assert.IsInstanceOfType<FlowAttributes> (instance, "variable 'instance' is a FlowAttributes");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ProcessId'
        /// </summary>
        [Test]
        public void ProcessIdTest()
        {
            // TODO unit test for the property 'ProcessId'
        }
        /// <summary>
        /// Test the property 'FromObjectId'
        /// </summary>
        [Test]
        public void FromObjectIdTest()
        {
            // TODO unit test for the property 'FromObjectId'
        }
        /// <summary>
        /// Test the property 'FromObjectType'
        /// </summary>
        [Test]
        public void FromObjectTypeTest()
        {
            // TODO unit test for the property 'FromObjectType'
        }
        /// <summary>
        /// Test the property 'ToObjectId'
        /// </summary>
        [Test]
        public void ToObjectIdTest()
        {
            // TODO unit test for the property 'ToObjectId'
        }
        /// <summary>
        /// Test the property 'ToObjectType'
        /// </summary>
        [Test]
        public void ToObjectTypeTest()
        {
            // TODO unit test for the property 'ToObjectType'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Test]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }
        /// <summary>
        /// Test the property '_Default'
        /// </summary>
        [Test]
        public void _DefaultTest()
        {
            // TODO unit test for the property '_Default'
        }
        /// <summary>
        /// Test the property 'Optional'
        /// </summary>
        [Test]
        public void OptionalTest()
        {
            // TODO unit test for the property 'Optional'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
