/* 
 * ProcessMaker API
 *
 * This ProcessMaker I/O API provides access to a BPMN 2.0 compliant workflow engine api that is designed to be used as a microservice to support enterprise cloud applications.  The current Alpha 1.0 version supports most of the descriptive class of the BPMN 2.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@processmaker.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProcessMaker.PMIO.Api;
using ProcessMaker.PMIO.Model;
using ProcessMaker.PMIO.Client;
using System.Reflection;

namespace ProcessMaker.PMIO.Test
{
    /// <summary>
    ///  Class for testing ProcessAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProcessAttributesTests
    {
        // TODO uncomment below to declare an instance variable for ProcessAttributes
        //private ProcessAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProcessAttributes
            //instance = new ProcessAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProcessAttributes
        /// </summary>
        [Test]
        public void ProcessAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProcessAttributes
            //Assert.IsInstanceOfType<ProcessAttributes> (instance, "variable 'instance' is a ProcessAttributes");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ParentProcessId'
        /// </summary>
        [Test]
        public void ParentProcessIdTest()
        {
            // TODO unit test for the property 'ParentProcessId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'DurationBy'
        /// </summary>
        [Test]
        public void DurationByTest()
        {
            // TODO unit test for the property 'DurationBy'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Assignment'
        /// </summary>
        [Test]
        public void AssignmentTest()
        {
            // TODO unit test for the property 'Assignment'
        }
        /// <summary>
        /// Test the property 'DesignAccess'
        /// </summary>
        [Test]
        public void DesignAccessTest()
        {
            // TODO unit test for the property 'DesignAccess'
        }
        /// <summary>
        /// Test the property 'ShowMap'
        /// </summary>
        [Test]
        public void ShowMapTest()
        {
            // TODO unit test for the property 'ShowMap'
        }
        /// <summary>
        /// Test the property 'ShowMessage'
        /// </summary>
        [Test]
        public void ShowMessageTest()
        {
            // TODO unit test for the property 'ShowMessage'
        }
        /// <summary>
        /// Test the property 'ShowDelegate'
        /// </summary>
        [Test]
        public void ShowDelegateTest()
        {
            // TODO unit test for the property 'ShowDelegate'
        }
        /// <summary>
        /// Test the property 'ShowDynaform'
        /// </summary>
        [Test]
        public void ShowDynaformTest()
        {
            // TODO unit test for the property 'ShowDynaform'
        }
        /// <summary>
        /// Test the property 'CategoryId'
        /// </summary>
        [Test]
        public void CategoryIdTest()
        {
            // TODO unit test for the property 'CategoryId'
        }
        /// <summary>
        /// Test the property 'SubCategoryId'
        /// </summary>
        [Test]
        public void SubCategoryIdTest()
        {
            // TODO unit test for the property 'SubCategoryId'
        }
        /// <summary>
        /// Test the property 'CreateUserId'
        /// </summary>
        [Test]
        public void CreateUserIdTest()
        {
            // TODO unit test for the property 'CreateUserId'
        }
        /// <summary>
        /// Test the property 'Debug'
        /// </summary>
        [Test]
        public void DebugTest()
        {
            // TODO unit test for the property 'Debug'
        }
        /// <summary>
        /// Test the property 'DynaformSummaryId'
        /// </summary>
        [Test]
        public void DynaformSummaryIdTest()
        {
            // TODO unit test for the property 'DynaformSummaryId'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
