/* 
 * ProcessMaker API
 *
 * This ProcessMaker I/O API provides access to a BPMN 2.0 compliant workflow engine api that is designed to be used as a microservice to support enterprise cloud applications.  The current Alpha 1.0 version supports most of the descriptive class of the BPMN 2.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@processmaker.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProcessMaker.PMIO.Api;
using ProcessMaker.PMIO.Model;
using ProcessMaker.PMIO.Client;
using System.Reflection;

namespace ProcessMaker.PMIO.Test
{
    /// <summary>
    ///  Class for testing TaskInstanceAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TaskInstanceAttributesTests
    {
        // TODO uncomment below to declare an instance variable for TaskInstanceAttributes
        //private TaskInstanceAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TaskInstanceAttributes
            //instance = new TaskInstanceAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaskInstanceAttributes
        /// </summary>
        [Test]
        public void TaskInstanceAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TaskInstanceAttributes
            //Assert.IsInstanceOfType<TaskInstanceAttributes> (instance, "variable 'instance' is a TaskInstanceAttributes");
        }

        /// <summary>
        /// Test the property 'TaskId'
        /// </summary>
        [Test]
        public void TaskIdTest()
        {
            // TODO unit test for the property 'TaskId'
        }
        /// <summary>
        /// Test the property 'InstanceId'
        /// </summary>
        [Test]
        public void InstanceIdTest()
        {
            // TODO unit test for the property 'InstanceId'
        }
        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Test]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Test]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'DelegateDate'
        /// </summary>
        [Test]
        public void DelegateDateTest()
        {
            // TODO unit test for the property 'DelegateDate'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'FinishDate'
        /// </summary>
        [Test]
        public void FinishDateTest()
        {
            // TODO unit test for the property 'FinishDate'
        }
        /// <summary>
        /// Test the property 'TaskDueDate'
        /// </summary>
        [Test]
        public void TaskDueDateTest()
        {
            // TODO unit test for the property 'TaskDueDate'
        }
        /// <summary>
        /// Test the property 'RiskDate'
        /// </summary>
        [Test]
        public void RiskDateTest()
        {
            // TODO unit test for the property 'RiskDate'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'InstanceOverduePercentage'
        /// </summary>
        [Test]
        public void InstanceOverduePercentageTest()
        {
            // TODO unit test for the property 'InstanceOverduePercentage'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
