/* 
 * ProcessMaker API
 *
 * This ProcessMaker I/O API provides access to a BPMN 2.0 compliant workflow engine api that is designed to be used as a microservice to support enterprise cloud applications.  The current Alpha 1.0 version supports most of the descriptive class of the BPMN 2.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@processmaker.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProcessMaker.PMIO.Api;
using ProcessMaker.PMIO.Model;
using ProcessMaker.PMIO.Client;
using System.Reflection;

namespace ProcessMaker.PMIO.Test
{
    /// <summary>
    ///  Class for testing TaskAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TaskAttributesTests
    {
        // TODO uncomment below to declare an instance variable for TaskAttributes
        //private TaskAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TaskAttributes
            //instance = new TaskAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaskAttributes
        /// </summary>
        [Test]
        public void TaskAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TaskAttributes
            //Assert.IsInstanceOfType<TaskAttributes> (instance, "variable 'instance' is a TaskAttributes");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ProcessId'
        /// </summary>
        [Test]
        public void ProcessIdTest()
        {
            // TODO unit test for the property 'ProcessId'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'AssignType'
        /// </summary>
        [Test]
        public void AssignTypeTest()
        {
            // TODO unit test for the property 'AssignType'
        }
        /// <summary>
        /// Test the property 'PriorityVariable'
        /// </summary>
        [Test]
        public void PriorityVariableTest()
        {
            // TODO unit test for the property 'PriorityVariable'
        }
        /// <summary>
        /// Test the property 'AssignVariable'
        /// </summary>
        [Test]
        public void AssignVariableTest()
        {
            // TODO unit test for the property 'AssignVariable'
        }
        /// <summary>
        /// Test the property 'GroupVariable'
        /// </summary>
        [Test]
        public void GroupVariableTest()
        {
            // TODO unit test for the property 'GroupVariable'
        }
        /// <summary>
        /// Test the property 'MiInstanceVariable'
        /// </summary>
        [Test]
        public void MiInstanceVariableTest()
        {
            // TODO unit test for the property 'MiInstanceVariable'
        }
        /// <summary>
        /// Test the property 'MiCompleteVariable'
        /// </summary>
        [Test]
        public void MiCompleteVariableTest()
        {
            // TODO unit test for the property 'MiCompleteVariable'
        }
        /// <summary>
        /// Test the property 'TransferFly'
        /// </summary>
        [Test]
        public void TransferFlyTest()
        {
            // TODO unit test for the property 'TransferFly'
        }
        /// <summary>
        /// Test the property 'CanUpload'
        /// </summary>
        [Test]
        public void CanUploadTest()
        {
            // TODO unit test for the property 'CanUpload'
        }
        /// <summary>
        /// Test the property 'ViewUpload'
        /// </summary>
        [Test]
        public void ViewUploadTest()
        {
            // TODO unit test for the property 'ViewUpload'
        }
        /// <summary>
        /// Test the property 'ViewAdditionalDocumentation'
        /// </summary>
        [Test]
        public void ViewAdditionalDocumentationTest()
        {
            // TODO unit test for the property 'ViewAdditionalDocumentation'
        }
        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Test]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }
        /// <summary>
        /// Test the property 'SendLastEmail'
        /// </summary>
        [Test]
        public void SendLastEmailTest()
        {
            // TODO unit test for the property 'SendLastEmail'
        }
        /// <summary>
        /// Test the property 'DerivationScreenTpl'
        /// </summary>
        [Test]
        public void DerivationScreenTplTest()
        {
            // TODO unit test for the property 'DerivationScreenTpl'
        }
        /// <summary>
        /// Test the property 'SelfserviceTimeout'
        /// </summary>
        [Test]
        public void SelfserviceTimeoutTest()
        {
            // TODO unit test for the property 'SelfserviceTimeout'
        }
        /// <summary>
        /// Test the property 'SelfserviceTime'
        /// </summary>
        [Test]
        public void SelfserviceTimeTest()
        {
            // TODO unit test for the property 'SelfserviceTime'
        }
        /// <summary>
        /// Test the property 'SelfserviceTimeUnit'
        /// </summary>
        [Test]
        public void SelfserviceTimeUnitTest()
        {
            // TODO unit test for the property 'SelfserviceTimeUnit'
        }
        /// <summary>
        /// Test the property 'SelfserviceExecution'
        /// </summary>
        [Test]
        public void SelfserviceExecutionTest()
        {
            // TODO unit test for the property 'SelfserviceExecution'
        }
        /// <summary>
        /// Test the property 'LastAssignedUserId'
        /// </summary>
        [Test]
        public void LastAssignedUserIdTest()
        {
            // TODO unit test for the property 'LastAssignedUserId'
        }
        /// <summary>
        /// Test the property 'Script'
        /// </summary>
        [Test]
        public void ScriptTest()
        {
            // TODO unit test for the property 'Script'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
